-- ==========================================================================
--  Carga de contexto de negocio T1 (T1 Global + cada producto)
--  Fuente: t1-contexto-negocio.md · Ejecútala en Supabase → SQL Editor.
--  Idempotente: actualiza el `contexto`, respeta el `objetivo_anual` que ya
--  hayas escrito, y crea los que falten. Corre las veces que quieras.
--  Nota: hace match por nombre EXACTO ('T1 Tienda', 'T1 Envíos', 'T1 Pagos',
--  etc). Si ya renombraste alguno, avísame antes de correrla.
-- ==========================================================================
do $body$
declare
  uid uuid;
  rec record;
begin
  select id into uid from public.users limit 1;
  if uid is null then
    raise exception 'No hay usuario en public.users. Entra a la app primero.';
  end if;

  for rec in
    select * from (values
      (0, 'T1 Global', $c$T1 es un ecosistema de comercio AI-first para México y LATAM que ayuda a los negocios a lanzar, operar, escalar y optimizar su comercio. Tesis central: la ventaja de ecosistema — productos que valen más juntos que aislados, sobre infraestructura compartida (T1 Cuenta: un registro, una base de clientes, roles/permisos configurables, documentos, canales; regla 1 cuenta = 1 negocio, datos compartidos entre productos). Capas del ecosistema: operación de tienda/comercio, orquestación de envíos y logística, pagos y ruteo, inteligencia de riesgo/fraude (T1Score), operación financiera y facturación CFDI (T1 Finanzas) y habilitación comercial vía T1Partners. Segmentos: emprendedores/PyMEs (freemium, velocidad, simplicidad), merchants en crecimiento (control, automatización, multicanal, visibilidad), Enterprise (orquestación, integración, escala, reportería, co-venta con el equipo comercial) y Partners (agencias, consultores, resellers que activan clientes). Modelo de negocio: freemium de entrada (esp. Finanzas, 30 timbres/mes gratis), suscripción por planes (Tienda), cobro por uso/valor (Envíos por valor de envío, Pagos por transacción), economía de ecosistema (el compounding permite precios individuales agresivos; el valor se captura por stickiness y expansión cruzada) y canal de partners como palanca de alto apalancamiento. Diferenciadores núcleo: integración de ecosistema única en México (comercio + logística + pagos + facturación en una plataforma), IA como núcleo (no features superficiales), mejor UX/UI, precios agresivos/freemium, multi-segmento (del emprendedor solo al Enterprise) y seguridad/calidad grado enterprise. Ambición de largo plazo: ser infraestructura fundacional del comercio. Tono: directo, práctico, systems-thinking sin jerga, confiado sin sobre-prometer; nunca hype, claims de "#1" sin sustento, "revolucionario/game-changing", ni garantías de resultados, ni atacar competidores. Owners: Tienda→Alonso · Envíos→Antar · Pagos→Steb · Score→José Luis · Finanzas→Arturo · Partners→Antar.$c$,
       $o$Consolidar la ventaja de ecosistema: aumentar los clientes con más de un producto (cross-sell), con T1 Finanzas como entrada de mayor volumen y Envíos/Pagos como expansión. (Reemplaza con tus KPIs reales del año.)$o$),

      (1, 'T1 Tienda', $c$Categoría: capa de operaciones de comercio. Owner: Alonso. Una línea: capa de operación de comercio para que los merchants creen, gestionen y escalen venta online en storefronts propios y canales conectados — NO un simple creador de sitios. Problema: merchants operando con herramientas fragmentadas y procesos manuales (storefront, marketplaces, catálogos, inventario/precios, reportería) → trabajo duplicado, ejecución lenta, información inconsistente entre canales, alta carga operativa. Capacidades: creación y gestión de storefront, setup asistido por IA, gestión de producto/catálogo, operación multicanal (Shopify, Tiendanube, Mercado Libre, Amazon), dashboard operativo y reportería. Escala: de emprendedor a Enterprise. Rol en el ecosistema: punto de entrada principal y superficie de expansión del merchant — sus órdenes fluyen a T1 Envíos (envío) y T1 Finanzas (auto-facturación), sus pagos a T1 Pagos, datos de cliente vía módulo Clientes. Diferenciadores: mentalidad de operación (no solo crear sitio), velocidad de lanzamiento asistida por IA, lógica operativa multicanal/marketplace, camino de expansión nativo del ecosistema. Compite con: Shopify, VTEX, Salesforce Commerce. Guardrails: NO "creador de sitios" ni "generación automática de negocio con IA"; SÍ capa de operación de comercio, IA que reduce fricción de lanzamiento, control operativo multicanal.$c$,
       ''),

      (2, 'T1 Envíos', $c$Categoría: capa de operaciones de envíos y logística. Owner: Antar. Una línea: orquestación multi-paquetería y control operativo para gestionar envíos con mejor visibilidad, calidad de servicio y control — no solo generar guías. Problema: la operación de envíos se fragmenta al crecer — múltiples paqueterías con flujos inconsistentes, gestión manual, baja visibilidad de incidencias, reportería débil, seguimiento manual con la paquetería, errores operativos (sobrepesos, mismatches), falta de ruteo/orquestación flexible. Capacidades: operación multi-paquetería, generación y gestión de envíos, orquestación por reglas (ruteo por peso/destino/lógica de servicio), visibilidad y reportería operativa, Control de Calidad (incidencias, sobrepesos, excepciones) y colaboración operativa del lado de la paquetería. Escala: de decenas a cientos de miles de envíos/mes; Enterprise = más de 5,000 envíos/mes. Rol en el ecosistema: recibe órdenes de T1 Tienda; costos de envío y Carta Porte se conectan con T1 Finanzas (Fase 2); partners activan vía T1Partners. Diferenciadores: enfoque operations-first (no solo guías), orquestación para lógica compleja, framing de Control de Calidad, coordinación merchant + paquetería, fit flexible por segmento. Guardrails: NO "generador barato de guías", "comparador de tarifas", "magia logística con IA", ni "mejor/más barato" sin prueba aprobada; la IA es enhancer, no el pitch principal.$c$,
       ''),

      (3, 'T1 Pagos', $c$Categoría: capa de operaciones de pagos. Owner: Steb. Una línea: capa de operación e infraestructura de pagos para aceptar, gestionar y optimizar flujos de pago — no solo un gateway. Problema: el pago se trata como simple cobro, pero al crecer se vuelve crítico y fragmentado — poca flexibilidad, baja visibilidad de performance, herramientas fragmentadas, dependencia de un solo proveedor sin optimización, tareas manuales, mala coordinación entre pagos, comercio y riesgo. Capacidades: aceptación y procesamiento de pagos, Payment Links (punto de entrada comercial clave), experiencias de checkout, gestión de operaciones, orquestación/ruteo avanzado, infraestructura de dispersión OPM (cuentas de comercio bajo cuenta maestra T1, en vivo) y conexión a T1Score para fraude/riesgo. Métodos: tarjetas, SPEI, MSI. Escala: clientes con cientos de miles de transacciones mensuales. Rol en el ecosistema: pagos para órdenes de T1 Tienda; OPM reutilizable por T1 Finanzas (pagos a proveedores, Fase 2); inteligencia de riesgo desde T1Score; puede ser entrada directa (payment links) o expansión tras Tienda. Diferenciadores: framing operations-first, puntos de entrada flexibles, camino a orquestación/optimización, conexión nativa a inteligencia de riesgo. Guardrails: NO "solo payment links", "reemplazo de gateway", "tasas de aprobación garantizadas" ni "magia de pagos con IA"; SÍ capa de operación de pagos con control y riesgo conectado.$c$,
       ''),

      (4, 'T1Score', $c$Categoría: capa de inteligencia de riesgo, fraude y scoring. Owner: José Luis. Una línea: producto STANDALONE de inteligencia y soporte a decisiones para flujos sensibles al riesgo (pagos, fraude, onboarding, crédito) — NO un toggle de antifraude dentro de T1 Pagos. Problema: decisiones de riesgo con señales incompletas, herramientas fragmentadas, revisión manual lenta, reglas rígidas sin contexto → falsos positivos/negativos, pérdidas por fraude evitables, baja calidad de aprobación, decisiones inconsistentes. Capacidades: inteligencia de fraude y riesgo, lógica de scoring y soporte a decisiones, casos de riesgo de pago (con T1 Pagos), scoring de crédito/riesgo, inteligencia enriquecida con datos alternativos e integración en los flujos del cliente. Rol en el ecosistema: provee inteligencia a T1 Pagos; conexión futura a T1 Identity (KYC) y T1 Capital (crédito); diferenciador estratégico de las jugadas de pagos e identidad. Diferenciadores: standalone (no feature de pagos), multi-caso de uso, enriquecimiento con datos alternativos. Compite con: antifraude / motores de reglas / burós (posicionado como inteligencia + integración, NO buró ni verificación de identidad). Guardrails: NO "buró de crédito", NO "verificación de identidad" (eso es T1 Identity), NO "IA que elimina el fraude".$c$,
       ''),

      (5, 'T1 Finanzas', $c$Categoría: operaciones financieras (facturación / CFDI / SAT). Owner: Arturo. Estado: NUEVO, en desarrollo (Fase 1). Una línea: plataforma de facturación CFDI 4.0, integración con el SAT y operación financiera; el punto de entrada de MAYOR VOLUMEN al ecosistema (facturar es universal para todo negocio formal en México). Problema: facturación y operación fiscal fragmentada/manual para PyMEs, falta de facturación integrada al comercio, gestión dispersa de CFDIs emitidos y recibidos. Capacidades (Fase 1): emisión de CFDI (Ingreso, Egreso, Complemento de Pago 2.0, Factura Global), cancelación con flujo SAT, descarga masiva de facturas recibidas, auto-facturación desde T1 Tienda y canales externos, portal público de auto-factura, facturación masiva CSV/Excel, mapeo de ClaveProdServ con IA y rol Contador. Freemium: 30 timbres/mes gratis. Rol en el ecosistema: auto-factura órdenes de Tienda; Fase 2 conecta pagos a proveedores (OPM de Pagos) y costos de envío (Envíos); a futuro su data CFDI alimenta T1Score y T1 Capital para scoring de crédito. Diferenciadores: entrada freemium de altísimo volumen, auto-facturación nativa desde comercio, IA para ClaveProdServ, integración SAT completa. Guardrails: mantener claims fiscales precisos; no prometer capacidades de Fase 2 como disponibles hoy.$c$,
       ''),

      (6, 'T1Partners', $c$Categoría: programa de habilitación de socios (canal go-to-market). Owner: Antar. Una línea: programa para que profesionales y empresas externas refieran y activen negocios en T1, con comisiones recurrentes + ingresos por servicios propios. Filosofía: referidos + activación, no solo leads — un referido solo vale cuando el cliente activa. Perfiles: profesionales digitales/consultores/agencias, ejecutivos comerciales/conectores, afiliados/creadores/comunidades, recién egresados/emprendedores. Modelo de comisiones (verificar términos vigentes): T1 Tienda 25% del plan activo, 3 años, hold 60 días; T1 Envíos PyME 4% Año 1 / 2% Año 2 sobre valor de envío, 24 meses, hold 15 días; T1 Envíos Enterprise (>5k/mes) 2% Año 1 / 1% Año 2; T1 Pagos y T1Score no comisionables de forma independiente (supuesto — confirmar), se posicionan como valor de ecosistema. Doble monetización: comisiones recurrentes vía T1 + ingresos por servicios propios del partner (setup, migración, catálogo, onboarding de marketplace, payment links, dashboards, account management). Regla crítica Enterprise: se CO-VENDE con T1 — el partner abre y califica, T1 hace discovery, propuesta e implementación; el partner NO promete crédito, precios custom ni compromete términos. Mayor volumen esperado vía partners: T1 Finanzas (freemium + necesidad universal). Guardrails: no inventar features/roadmaps, no prometer resultados ni términos fuera de política, registrar referidos temprano para atribución.$c$,
       $o$$o$)
    ) as t(orden, nombre, contexto, objetivo)
  loop
    update public.negocios
       set contexto       = rec.contexto,
           objetivo_anual = coalesce(nullif(objetivo_anual, ''), nullif(rec.objetivo, '')),
           orden          = rec.orden
     where user_id = uid and nombre = rec.nombre;
    if not found then
      insert into public.negocios (user_id, nombre, contexto, objetivo_anual, orden)
      values (uid, rec.nombre, rec.contexto, nullif(rec.objetivo, ''), rec.orden);
    end if;
  end loop;
end $body$;
